### ISSUE TITLE
Possible Addon for Chakra (Naruto)

### ISSUE THREAD

**Issue by theKross** [ltouroumov/worm-cyoa-v6-fork#26]
I think it could be interesting to have an Addon for Chakra (Naruto) due to Ki (Dragon Ball) and Reiryoku (Bleach),
Chakra is meant to be the combination of physical energy and spiritual energy, Ki (Dragon Ball) could be an upgraded physical energy and Reiryoku (Bleach) could be an upgraded spiritual energy. Linking all three like the Addon Mythical of Aura (RWBY) that link it with Reiryoku (Bleach).

Edit: Thinking more on it, the Addon could be something like Star Chakra that add a 'form' to Chakra similar to Hoshigakure's Mysterious Peacock Method, with the same bonus to Ki and Reiryoku similar to Black Goku's Spirit Blade.

**Comment by mnster** [comment]
I gotchu, made Chakra Formation a few weeks ago.
